---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
```

```{r}
sd_population <- 30

mean_control_population <- 140
mean_drug_population <- 160

dif_population <- mean_drug_population - mean_control_population

cohen_d_population <- dif_population / sd_population
cohen_d_population
```

```{r}

```

```{r}
n_control <- 20
n_drug <- 15

dat_control <- tibble(subject = 1:n_control) |> 
  mutate(blood_pressure = rnorm(n(), mean = mean_control_population, sd = sd_population), 
         cond = "control")

dat_drug <- tibble(subject = 1:n_drug) |> 
  mutate(blood_pressure = rnorm(n(), mean = mean_drug_population, sd = sd_population), 
         cond = "drug")

dat <- dat_control |> 
  bind_rows(dat_drug)

dat |>
  ggplot(aes(x = cond, y = blood_pressure)) +
  geom_point()
```

```{r}
sd_control <- dat_control |> 
  summarise(sd = sd(blood_pressure)) |> 
  pull()

#sd_control <- sd(dat_control$blood_pressure)

sd_drug <- dat_drug |> 
  summarise(sd = sd(blood_pressure)) |> 
  pull()

var <- ( (n_control - 1) * sd_control^2 + (n_drug - 1) * sd_drug^2 ) / (n_control + n_drug - 2)

sd <- sqrt(var)


summaries <- dat |> 
  group_by(cond) |> 
  summarise(mean = mean(blood_pressure), 
            sd = sd(blood_pressure), 
            n = n()) |> 
  pivot_wider(values_from = c(mean, sd, n), names_from = cond) |> 
  mutate(dif_mean = mean_drug - mean_control, 
         sd = sqrt(( (n_control - 1) * sd_control^2 + (n_drug - 1) * sd_drug^2 ) / (n_control + n_drug - 2)), 
         cohen_d = dif_mean / sd)

```

```{r}
create_summary_fun <- function(.data, .x, .group) {
  .data |> 
  group_by({{.group}}) |> 
  summarise(mean = mean({{.x}}), 
            sd = sd({{.x}}), 
            n = n()) |> 
  pivot_wider(values_from = c(mean, sd, n), names_from = cond) |> 
  mutate(dif_mean = mean_drug - mean_control, 
         sd = sqrt(( (n_control - 1) * sd_control^2 + (n_drug - 1) * sd_drug^2 ) / (n_control + n_drug - 2)), 
         cohen_d = dif_mean / sd, 
         g = cohen_d * (1- (3)/(4*(n_drug + n_control) - 9)))
}

create_summary_fun(dat, blood_pressure, cond)
```


```{r}
n_samples <- 1000
samples_control <- tibble(sample = 1:n_samples) |> 
  group_by(sample) |> 
  summarise(blood_pressure = rnorm(n_control, mean = mean_control_population, sd = sd_population), 
            .groups = "keep") |> 
  mutate(cond = "control")

samples_drug <- tibble(sample = 1:n_samples) |> 
  group_by(sample) |> 
  summarise(blood_pressure = rnorm(n_drug, mean = mean_drug_population, sd = sd_population),
            .groups = "keep") |> 
  mutate(cond = "drug")

samples <- samples_control |> 
  bind_rows(samples_drug)
```

```{r}
summary_samples <- samples |> 
  group_by(sample) |> 
  nest() |> 
  rowwise() |> 
  mutate(summary = list(create_summary_fun(data, blood_pressure, cond))) |> 
  select(-data) |> 
  unnest(summary)

summary_samples
```

```{r}
summary_samples |> 
  ggplot(aes(cohen_d)) +
  geom_histogram(bins = 50) +
  geom_vline(xintercept = cohen_d_population, color = "red")
```
```{r}
summary_samples |> 
  ungroup() |> 
  summarise(m = mean(cohen_d), 
            m_g = mean(g))
```

